IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'AdBillingMaster' AND type = 'U')
BEGIN
    CREATE TABLE AdBillingMaster (
        BillingID INT IDENTITY(1,1) PRIMARY KEY,
        Uniquekey NVARCHAR(300) NOT NULL,
        BranchName NVARCHAR(100) NOT NULL,
        ContractorCode NVARCHAR(50) NOT NULL,
        ContractorAgencyName NVARCHAR(150) NOT NULL,
        ContractorEmailID NVARCHAR(100) NULL,
        ContractorContactNo NVARCHAR(20) NOT NULL,
        OwnerName NVARCHAR(100) NULL,
        LONumberCrRemarks NVARCHAR(200) NULL,
        SiteProjectName NVARCHAR(200) NULL,
        VoucherType NVARCHAR(100) NULL,
        WorkOrderNo NVARCHAR(100) NULL,
        WorkOrderDate DATE NULL,
        TCVValue DECIMAL(18,2) NULL,
        BillSentDate DATE NULL,
        BillNoDebRemarks NVARCHAR(200) NULL,
        BillDate DATE NULL,
        BillAmount DECIMAL(18,2) NULL,
        BillStage NVARCHAR(50) NULL,
        BillRecdDate DATE NULL,
        ProjectPayment NVARCHAR(100) NULL,
        ZohoDoc NVARCHAR(200) NULL,
        TallyName NVARCHAR(100) NULL,
        InstRemarks NVARCHAR(200) NULL,
        BillGivenHOD NVARCHAR(100) NULL,
        BillRecdFromHOD NVARCHAR(100) NULL,
        BillSubmittedToAcctDate DATE NULL,
        AccountNumber NVARCHAR(50) NULL,
        BankName NVARCHAR(100) NULL,
        IFSCCode NVARCHAR(20) NULL,
        PANNumber NVARCHAR(20) NULL,
        TDS NVARCHAR(50) NULL,
        EWT NVARCHAR(50) NULL,
        GST NVARCHAR(50) NULL,
        PayableAmount DECIMAL(18,2) NULL,
        PaymentDate DATE NULL,
        UTRNumber NVARCHAR(100) NULL,
        StatusInfo NVARCHAR(200) NULL,
        AcctRemarks NVARCHAR(200) NULL,
        CreatedBy NVARCHAR(100) NULL,
        CreatedDate DATETIME NULL,
        ModifiedBy NVARCHAR(100) NULL,
        ModifiedDate DATETIME NULL
    );
END
